import type { SearchDocument } from "./types";

/** Demo corpus until PostgreSQL sync is wired. */
export const SEED_SEARCH_DOCUMENTS: SearchDocument[] = [
  {
    id: "stem_antwerp_rhodes",
    type: "stem",
    title: "Antwerp Brushed Rhodes",
    subtitle: "by Sólveig Tinde · 14 stems",
    tags: ["rhodes", "antwerp", "marketplace"],
    bpm: 96,
    key: "A minor",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "producer_lou_marsden",
    type: "producer",
    title: "Lou Marsden",
    subtitle: "Vocal sketch · Amsterdam",
    tags: ["vocal", "collab"],
    bpm: null,
    key: null,
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "session_velvet_clip",
    type: "session",
    title: "Velvet Clip — V12",
    subtitle: "Resume from bar 47 · Margot",
    tags: ["session", "velvet", "daw"],
    bpm: 92,
    key: "D♭ minor",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "twin_margot",
    type: "twin",
    title: "Margot Chen · Twin",
    subtitle: "Composition & marketplace graph",
    tags: ["twin", "creator"],
    bpm: null,
    key: null,
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "composition_quiet_hours",
    type: "composition",
    title: "Quiet Hours",
    subtitle: "by Margot · full session",
    tags: ["composition", "midi", "stems"],
    bpm: 78,
    key: "C major",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "midi_velvet_bass",
    type: "midi",
    title: "velvet_clip.mid — bass lane",
    subtitle: "Patterns · 1/16 grid",
    tags: ["midi", "bass", "velvet"],
    bpm: 92,
    key: "D♭ minor",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "vocal_linnen_pack",
    type: "vocal",
    title: "Linnen Vocal Pack",
    subtitle: "by Lou Marsden · 21 takes",
    tags: ["vocal", "dry", "wet"],
    bpm: 84,
    key: "F♯ major",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "loop_pol_snare",
    type: "loop",
    title: "Pol. Late Snare Library",
    subtitle: "by Tomek Iłła · 62 one-shots",
    tags: ["drums", "snare", "one-shot"],
    bpm: null,
    key: null,
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "stem_velvet_subs",
    type: "stem",
    title: "Velvet Subs Vol. 2",
    subtitle: "by Eos Veil · 10 stems",
    tags: ["808", "sub", "velvet"],
    bpm: 92,
    key: "D♭ minor",
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
  {
    id: "producer_eos_veil",
    type: "producer",
    title: "Eos Veil",
    subtitle: "Arrangement · Warsaw",
    tags: ["producer", "arrangement"],
    bpm: null,
    key: null,
    updatedAt: Date.now(),
    sourceId: null,
    sourceTable: null,
  },
];
